name: Clear Cache Weekly

on:
  schedule:
    - cron: '0 11 * * 4'  # 木曜 20:00 JST
    - cron: '0 3  * * 5'  # 金曜 12:00 JST
    - cron: '0 3  * * 6'  # 土曜 12:00 JST
    - cron: '0 3  * * 0'  # 日曜 12:00 JST

  workflow_dispatch:  # ← 手動実行も可！

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: |
          pip install gspread oauth2client

      - name: Run clear_cache.py
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          python clear_cache.py
